Cool things to do with Numpy:
* Create arrays (`np.array()`)
* Matrix multiply(`np.matmul()`)
* Dot product of vectors (`np.dot()`)
* Kronecker product (Tensor product) (`np.kron()`) 
* check if two matrices equal (`np.all()`)
* transpose (`np.transpose()`)
* find norm of vector (`numpy.linalg.norm()`)
* reshape an array (`np.reshape()`)

    
    

- List of numbers between a given range 
- List of random number
- List of random number between range 
- Pick a random number from a random list 
- Pick a random between a range
- All zeros, ones, constants and alternate
- Progressions: Arithmatic, Geometric, Hormonic progression

In [1]:
import numpy as np

### List of random numbers: 

In [24]:
list01 = np.random.randint(low=0,high=10,size=10) # between -0 to 9
print(list01)

list01 = np.random.randint(low=-10,high=11,size=10) # between -10 to 10
print(list01)

list01 = np.random.randint(low=-10,high=11,size=1) # Only 1 value between -10 to 10
print(list01[0])

[6 1 7 4 5 0 2 2 8 8]
[ -8 -10   1  -8  -2 -10  -2  -7   2  -2]
-9


In [8]:
list01 = np.random.rand(5) # floating point
print(list01)

[0.50957153 0.82497398 0.68861144 0.75468974 0.75425002]


In [28]:
list01 = np.random.rand(3,3) # with shape
print(list01)

print() 

list01 = np.random.randint(low=0,high=10,size=9) # Reshaped with integers
print(list01.reshape(3,3))


[[0.51340417 0.95306619 0.29757916]
 [0.78702803 0.27841934 0.15724281]
 [0.20376632 0.97462624 0.3962346 ]]

[[5 3 1]
 [4 3 9]
 [7 7 9]]


In [1]:
## Select 3 points from list of points
all_data = [0,1,2,3,4,5,6,7,8,9]
from random import shuffle
shuffle(all_data)
res = all_data[:3]# or any other number of items
print(res)

[6, 8, 5]


### All zeros, ones, constants and alternate:

In [29]:
list02 = np.zeros(10)
print(list02)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
list02 = np.ones(10) 
print(list02)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [34]:
list02 = np.ones(10) * 3.14
print(list02)

list02 = np.ones(10) * 10
print(list02)

list02 = np.random.randint(low=42,high=43,size=5) 
print(list02)


[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[42 42 42 42 42]


In [13]:
### Generate nagles between range [0,2pi) i.e exclude 2pi

import random, math

theta = random.uniform(0,2*math.pi)

print(theta)
print()

angles = [random.uniform(0,2*math.pi) for _ in range(10)] # 5 angles
print(angles)
print()

angles = np.array( [random.uniform(0,2*math.pi) for _ in range(5)] )
angles = np.around(angles, 2)
cos = np.cos(angles)
print(angles)
print(cos)
print()


4.349485090875334

[0.24519522096226132, 5.728486276079251, 0.48096545342377706, 1.8762748962959395, 0.6391854436841552, 5.507182929309845, 6.1386098237098725, 6.1382836584612654, 5.910722997474203, 0.6375434652706207]

[1.94 5.43 4.   3.4  5.12]
[-0.36087288  0.65758674 -0.65364362 -0.96679819  0.39641721]



### Progressions: Arithmatic, Geometric, Hormonic progression

In [42]:
list03 = np.arange(start=0, stop=1, step=0.1)
print(list03)

list03 = np.arange(start=0, stop=20, step=2)
print(list03)

list03 = np.arange(start=0, stop=1, step=0.1)
print(list03)


list03 = np.arange(start=0, stop=(np.pi+np.pi/8), step=0.125*np.pi) # 0 to pi with step = pi/8 including pi
print(list03)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.39269908 0.78539816 1.17809725 1.57079633 1.96349541
 2.35619449 2.74889357 3.14159265]


#### What is the difference between np.linspace and np.arange?

* np.arange allows you to define the stepsize 
* np.linspace allows you to define how many values you get including the specified min and max value 

In [44]:
np.linspace(start=0,stop=1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
np.arange(start=0,stop=1,step=0.25)

array([0.  , 0.25, 0.5 , 0.75])

### Random Stochastic matrix:

In [1]:
import numpy as np

def stochastic_matrix(x,y):
    w = np.random.rand(x*y)
    w = np.reshape(w,(x,y))
    w = w / np.sum(w,axis=0)
    return w
 
u = stochastic_matrix(3,3)
print(u)
print("Verification: ",u.sum(axis=0))

[[0.28753225 0.44495156 0.73617705]
 [0.2485788  0.5151379  0.1061739 ]
 [0.46388895 0.03991054 0.15764906]]
Verification:  [1. 1. 1.]


### generate statevector from binary sequence 

In [1]:
import numpy as np


def generate_state_vector_from_string(mystring):
    
    vi = [x for x in mystring]
    
    vec = np.array([[0],[0]])
    
    result_vector = np.array([])
    
    for i in range(len(vi)):   
        if(vi[i]=='0'): vec = np.array([[1],[0]])
        if(vi[i]=='1'): vec = np.array([[0],[1]])
            
        if (i==0): # Very important will go 1 less because kroneckr operations are only 3 not 4 
            result_vector = vec
        else:
            result_vector = np.kron(result_vector,vec)  # Calculating from left 
        # In an expression having 3 or more Tensor products, 
        # do you calculate from left or right? A (x) B (x) C is it AB (x) C  (Left) or A (x) BC  (Right)?

    return result_vector

u10 = generate_state_vector_from_string('1001')

print(u10)
print(np.shape(u10))

print()

u8 = generate_state_vector_from_string('0111')

print(u8)
print(np.shape(u8))

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
(16, 1)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
(16, 1)


In [3]:
import numpy as np
u = np.array([[0.4],[0.6]])
M = np.array([[0.5,1],[0.5,0]])

X = np.matmul(M,u)
X = np.matmul(M,X)
X = np.matmul(M,X)

print(X)

[[0.7]
 [0.3]]


# Other helpful commands:


In [17]:
# Very helpful commands in python:
import inspect
import numpy
from qiskit import Aer, execute
#dir(inspect)
#help(numpy.random.rand)
dir(Aer.aer)
inspect.getfullargspec(Aer.aer.get_backend)


['__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']