In [1]:
import numpy as np

In [3]:
p = np.array([[0],[1]])
op = np.array([[0.3,0.3],[0.7,0.7]])

for i in range(1000):
    p = np.matmul(op,p)

    
print(p)

[[0.3]
 [0.7]]


In [24]:
from random import randrange
heads = tails = 0
for i in range(1000):
    if randrange(100) <= 59:
        heads = heads + 1
    else:
        tails = tails + 1
print(heads,tails)

616 384


In [11]:
from random import randrange
a = b = c = randrange(100)
sum = a + b + c
state = [a/sum,b/sum,c/sum]
print(state)

[0.3333333333333333, 0.3333333333333333, 0.3333333333333333]


In [27]:
from random import randrange
a = randrange(100)
b = randrange(100-a)
c = 100 - a - b
state = [a,b,c]
print(state)

[92, 4, 4]


In [29]:
randrange(1,10)

5

In [49]:
from random import randrange 
heads = 0
tails = 0
for i in range(1000):
    x=randrange(1,11)
    #print(x)
    if x==10: 
        heads = heads + 1
        
    else: 
        tails = tails + 1
print(heads)
print(tails)

109
891


In [54]:
for i in range(30):
    print(randrange(5))

0
4
2
1
3
3
3
2
1
1
4
2
4
3
1
3
2
3
2
1
3
4
1
4
3
0
4
2
0
4


In [65]:
from random import randrange 
heads = tails = 0
for i in range(100):
    if randrange(5)==randrange(5): heads = heads + 1
    else: tails = tails + 1
print(tails)

77


In [55]:
x = np.array([[0.2,0.4],[0.8,0.6]])

state = np.array([[0.4],[0.6]])

state = np.matmul(x,state)
state = np.matmul(x,state)
state = np.matmul(x,state)

print(state)

[[0.3328]
 [0.6672]]


In [17]:
from random import randrange 
heads = 0
tails = 0
for i in range(1000):
    x = randrange(100) 
    if x < 75: heads = heads + 1
    else: tails = tails + 1
print(tails)

245


In [39]:
from random import randrange 

#T = randrange(100) 
#x = randrange(100) 

x = []
t = []

result = np.array([[1],[0]])

for i in range(1000000): 
    x.append(randrange(100))
    t.append(randrange(100))
    
for i in range(1000000):
    if(x[i]<t[i]):
        result[0][0] += 1
    else:
        result[1][0] += 1
    
print(result)
print()
print(result/1000000)

[[495289]
 [504712]]

[[0.495289]
 [0.504712]]


In [43]:
state = np.array([[0],[1]])
m = np.array([[0.99,0.03],[0.01,0.97]])


for i in range(10000):
    state = np.matmul(m,state)
    print(state)
    print()
    
print(state)    
    

[[0.03]
 [0.97]]

[[0.0588]
 [0.9412]]

[[0.086448]
 [0.913552]]

[[0.11299008]
 [0.88700992]]

[[0.13847048]
 [0.86152952]]

[[0.16293166]
 [0.83706834]]

[[0.18641439]
 [0.81358561]]

[[0.20895782]
 [0.79104218]]

[[0.2305995]
 [0.7694005]]

[[0.25137552]
 [0.74862448]]

[[0.2713205]
 [0.7286795]]

[[0.29046768]
 [0.70953232]]

[[0.30884897]
 [0.69115103]]

[[0.32649502]
 [0.67350498]]

[[0.34343522]
 [0.65656478]]

[[0.35969781]
 [0.64030219]]

[[0.37530989]
 [0.62469011]]

[[0.3902975]
 [0.6097025]]

[[0.4046856]
 [0.5953144]]

[[0.41849817]
 [0.58150183]]

[[0.43175825]
 [0.56824175]]

[[0.44448792]
 [0.55551208]]

[[0.4567084]
 [0.5432916]]

[[0.46844006]
 [0.53155994]]

[[0.47970246]
 [0.52029754]]

[[0.49051436]
 [0.50948564]]

[[0.50089379]
 [0.49910621]]

[[0.51085804]
 [0.48914196]]

[[0.52042372]
 [0.47957628]]

[[0.52960677]
 [0.47039323]]

[[0.5384225]
 [0.4615775]]

[[0.5468856]
 [0.4531144]]

[[0.55501017]
 [0.44498983]]

[[0.56280977]
 [0.43719023]]

[[0.57029738]
 [0.

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [0.25]]

[[0.75]
 [