<a href="https://qworld.net" target="_blank" align="left"><img src="../qworld/images/header.jpg"  align="left"></a>
$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\stateplus}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\stateminus}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\I}{ \mymatrix{rr}{1 & 0 \\ 0 & 1}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $
$ \newcommand{\pstate}[1]{ \lceil \mspace{-1mu} #1 \mspace{-1.5mu} \rfloor } $
$ \newcommand{\greenbit}[1] {\mathbf{{\color{green}#1}}} $
$ \newcommand{\bluebit}[1] {\mathbf{{\color{blue}#1}}} $
$ \newcommand{\redbit}[1] {\mathbf{{\color{red}#1}}} $
$ \newcommand{\brownbit}[1] {\mathbf{{\color{brown}#1}}} $
$ \newcommand{\blackbit}[1] {\mathbf{{\color{black}#1}}} $

<font style="font-size:28px;" align="left"><b>Coin Flip: A Probabilistic Bit </b></font>
<br>
_prepared by Abuzer Yakaryilmaz_
<br><br>
[<img src="../qworld/images/watch_lecture.jpg" align="left">](https://youtu.be/uGKHEsVcSEs)
<br><br><br>

<h3> A fair coin </h3>

A coin has two sides: <i>Heads</i> and <i>Tails</i>.

After flipping a coin, we get either Heads or Tails. We can represent these two different cases by a single bit:
<ul>
    <li> 0 represents Heads </li>
    <li> 1 represents Tails </li>
</ul>

<h3> Flipping a fair coin </h3>

If our coin is fair, then the probabilities of getting Heads and Tails are equal:

$ p= \dfrac{1}{2} = 0.5 $.

Flipping a fair coin can be represented as an operator:
<ul>
    <li> $ FairCoin(Heads) = \frac{1}{2} Heads + \frac{1}{2}Tails $ </li>
    <li> $ FairCoin(Tails) \mspace{10mu} = \frac{1}{2} Heads + \frac{1}{2}Tails $ </li>
</ul>

Here is its table representation:

$
FairCoin = \begin{array}{c|cc} \hookleftarrow & \mathbf{Heads} & \mathbf{Tails} \\ \hline \mathbf{Heads} & \dfrac{1}{2} & \dfrac{1}{2} \\  \mathbf{Tails} & \dfrac{1}{2} & \dfrac{1}{2}  \end{array} 
$

Here is the same table by using 0 and 1 as the states:

$
FairCoin = \begin{array}{c|cc} \hookleftarrow & \mathbf{0} & \mathbf{1} \\ \hline \mathbf{0} & \dfrac{1}{2} & \dfrac{1}{2} \\  \mathbf{1} & \dfrac{1}{2} & \dfrac{1}{2}  \end{array} 
$

<h3> Task 1: Simulating FairCoin in Python</h3>

Flip a fair coin 100 times. Calculate the total number of heads and tails, and then check the ratio of the number of heads and the number of tails.

Do the same experiment 1000 times.

Do the same experiment 10,000 times.

Do the same experiment 100,000 times.

Do your results get close to the ideal case (the numbers of heads and tails are equal)?

# Solved by Rajesh Swarnkar: 

In [33]:
import numpy as np 

# storage
experiment_set = [100, 1000, 10000, 100000]
ratio = []

# operator
fair_coin_operator = np.array([[0.5,0.5],[0.5,0.5]])

#initial_state
coin_state = np.array([[1],[0]]) # Assum the initial state was head 

print("Fair coin operator: \n",fair_coin_operator," and its shape is ",np.shape(fair_coin_operator))
print()

print("Initial coin state: \n",coin_state," and its shape is ",np.shape(coin_state))
print()

for eset in experiment_set:   
    for i in range(eset):
        # toss
        if np.random.randint(low=0,high=2,size=1)[0] == 0:   ## This might be wrong if the random was not uniform
            # We know that the toss was fair till now but we will operate with fair coin operator 
            coin_state = coin_state + np.matmul(fair_coin_operator,np.array([[1],[0]]))
        else:
            coin_state = coin_state + np.matmul(fair_coin_operator,np.array([[0],[1]]))
    
    # End of 1 set of experiemnt:        
    ratio.append(coin_state[0][0]/coin_state[1][0])

    
for i in range(len(experiment_set)):
    print("Trials=",experiment_set[i],"Ratio(PH/PT)=",ratio[i])

Fair coin operator: 
 [[0.5 0.5]
 [0.5 0.5]]  and its shape is  (2, 2)

Initial coin state: 
 [[1]
 [0]]  and its shape is  (2, 1)

Trials= 100 Ratio(PH/PT)= 1.02
Trials= 1000 Ratio(PH/PT)= 1.0018181818181817
Trials= 10000 Ratio(PH/PT)= 1.0001801801801802
Trials= 100000 Ratio(PH/PT)= 1.00001800180018


<a href="CS08_Coin_Flip_Solutions.ipynb#task1">click for our solution</a>

<h3> Flipping a biased coin </h3>

Our coin may have a bias. 

For example, the probability of getting heads is greater than the probability of getting tails.

Here is an example:

$
BiasedCoin = \begin{array}{c|cc} \hookleftarrow & \mathbf{Heads} & \mathbf{Tails} \\ \hline \mathbf{Heads} & 0.6 & 0.6 \\  \mathbf{Tails} & 0.4 & 0.4  \end{array}
$

By using 0 and 1 as the states:

$
BiasedCoin = \begin{array}{c|cc} \hookleftarrow & \mathbf{0} & \mathbf{1} \\ \hline \mathbf{0} & 0.6 & 0.6\\  \mathbf{1} & 0.4 & 0.4 \end{array}
$

<h3> Task 2: Simulating BiasedCoin in Python</h3>

Flip the following biased coin 100 times. Calculate the total numbers of heads and tails, and then check the ratio of the number of heads and the number of tails.

$
BiasedCoin = \begin{array}{c|cc} \hookleftarrow & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.6 \\  \mathbf{Tail} & 0.4 & 0.4  \end{array}
$


Do the same experiment 1000 times.

Do the same experiment 10,000 times.

Do the same experiment 100,000 times.

Do your results get close to the ideal case $ \mypar{ \dfrac{ \mbox{# of heads} }{ \mbox{# of tails} } = \dfrac{0.6}{0.4} = 1.50000000 } $?

In [5]:
import numpy as np 


# storage
experiment_set = [100, 1000, 10000, 100000]
ratio = []

# operator
#fair_coin_operator = np.array([[0.5,0.5],[0.5,0.5]])
biased_coin_operator = np.array([[0.6,0.6],[0.4,0.4]])

#biased_coin_operator = np.array([[0.6,0.4],[0.6,0.4]])
#biased_coin_operator = np.transpose(biased_coin_operator) # Important Please be aware of this

#initial_state
coin_state = np.array([[1],[0]]) # Assum the initial state was head 

print("Biased coin operator: \n",biased_coin_operator," and its shape is ",np.shape(biased_coin_operator))
print()

print("Initial coin state: \n",coin_state," and its shape is ",np.shape(coin_state))
print()

for eset in experiment_set:   
    for i in range(eset):
        # toss
        if np.random.randint(low=0,high=2,size=1)[0] == 0:   # This generates uniform randoms
            # We know that the toss was fair till now but we will operate with biased coin operator 
            coin_state = coin_state + np.matmul(biased_coin_operator,np.array([[1],[0]]))
        else:
            coin_state = coin_state + np.matmul(biased_coin_operator,np.array([[0],[1]]))
    
    # End of 1 set of experiemnt:        
    ratio.append(coin_state[0][0]/coin_state[1][0])

    
for i in range(len(experiment_set)):
    print("Trials=",experiment_set[i],"Ratio(PH/PT)=",ratio[i])


Biased coin operator: 
 [[0.6 0.6]
 [0.4 0.4]]  and its shape is  (2, 2)

Initial coin state: 
 [[1]
 [0]]  and its shape is  (2, 1)

Trials= 100 Ratio(PH/PT)= 1.5250000000000055
Trials= 1000 Ratio(PH/PT)= 1.5022727272727852
Trials= 10000 Ratio(PH/PT)= 1.5002252252253605
Trials= 100000 Ratio(PH/PT)= 1.500022502244856


<a href="CS08_Coin_Flip_Solutions.ipynb#task2">click for our solution</a>

---

<h3> Extra: Programming a biased coin </h3>

We use a simple method to create a biased coin.

First, we pick a range for the precision of probabilities, say $ N $, as $ N = 11, 101, 1001, \mbox{ or }, 10^k+1 $ for some $ k > 3 $.

Second, we pick the bias, say $ B $, as an integer in $ \{0,\ldots,N\} $.

We fix $ N $ and $ B $.

Third, we pick a random integer in $ \{0,1,\ldots,N-1\} $:
<ul>
    <li> if it is less than $ B $, we output "Heads" and </li>
    <li> if it is equal to or greater than $ B $, we output "Tails" </li>
</ul>
    
In this way, we have a biased coin "landing on" heads with probability $ \frac{B}{N} $ including 0 and 1.

Remark that we pick $ N = 10^k+1 $ as an odd number. In this way, the coin cannot be fair as long as $ B $ is an integer. Because, the half of an odd integer is not an integer.

<h3> Task 3 </h3>

Write a function to implement the described biased coin,

The inputs are integers $N>0$ and $ B \in \{0,\ldots,N\} $.

The output is either "Heads" or "Tails".

In [7]:
import numpy as np 

def biased_coin_toss(N,B):
    from random import randrange
    random_number = randrange(N)
    bias_h = B/N + 0.0 
    bias_t = 1 - bias_h
    bias_op = np.array([[bias_h,bias_h],[bias_t,bias_t]])
    return bias_op
    

N = 101
B = np.random.randint(low=0,high=N,size=1)[0] # between -0 to 9
print(N," ",B)

print(biased_coin_toss(N,B))


101   52
[[0.51485149 0.51485149]
 [0.48514851 0.48514851]]


<a href="CS08_Coin_Flip_Solutions.ipynb#task3">click for our solution</a>

<h3> Task 4</h3>

We use the biased coin described in Task 3. 

(You may use the function given <a href="CS08_Coin_Flip_Solutions.ipynb#task3">in the solution</a>.)

We pick $ N $ as 101.

Our task is to determine the value of $ B $ experimentially without looking its value directly.

Flip the (same) biased coin 500 times, collect the statistics, and then guess the bias.

Compare your guess with the actual bias by calculating the relative error in percentage (the absolute value of the difference divided by the real bias).

In [17]:
from random import randrange

N = 101
B = np.random.randint(low=0,high=N,size=1)[0] # between -0 to 9

print(B)
print()

total_tosses = 20

state = np.array([[1],[0]]) # initially is Head

for i in range(total_tosses):
    state = np.matmul(biased_coin_toss(N,B),state)

print(state)    


my_guess =  state[0][0]

real_bias = B/N

error = abs(my_guess-real_bias)/real_bias*100 

print("my guess is",my_guess)
print("real bias is",real_bias)
print("error (%) is",error)



76

[[0.75247525]
 [0.24752475]]
my guess is 0.7524752475247525
real bias is 0.7524752475247525
error (%) is 0.0


<a href="CS08_Coin_Flip_Solutions.ipynb#task4">click for our solution</a>