<a href="https://qworld.net" target="_blank" align="left"><img src="../qworld/images/header.jpg"  align="left"></a>
$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\stateplus}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\stateminus}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\I}{ \mymatrix{rr}{1 & 0 \\ 0 & 1}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $
$ \newcommand{\pstate}[1]{ \lceil \mspace{-1mu} #1 \mspace{-1.5mu} \rfloor } $
$ \newcommand{\greenbit}[1] {\mathbf{{\color{green}#1}}} $
$ \newcommand{\bluebit}[1] {\mathbf{{\color{blue}#1}}} $
$ \newcommand{\redbit}[1] {\mathbf{{\color{red}#1}}} $
$ \newcommand{\brownbit}[1] {\mathbf{{\color{brown}#1}}} $
$ \newcommand{\blackbit}[1] {\mathbf{{\color{black}#1}}} $

<font style="font-size:28px;" align="left"><b> Operators on Multiple Bits </b></font>
<br>
_prepared by Abuzer Yakaryilmaz_
<br><br>
[<img src="../qworld/images/watch_lecture.jpg" align="left">](https://youtu.be/vd21d1KTC5c)
<br><br><br>

We explain how to construct the operator of a composition system when we apply an operator to one bit or to a few bits of the composite system.

*Here we have a simple rule, we assume that the identity operator is applied on the rest of the bits.*

### Single bit operators

When we have two bits, then our system has four states and any operator of the system can be defined as a $ (4 \times 4) $-dimensional matrix.

For example, if we apply the probabilistic operator $ M =  \mymatrix{c}{ 0.3 & 0.6 \\ 0.7 & 0.4  } $ to the second bit, then how can we represent the corresponding $ (4 \times 4) $-dimensional matrix?

Since we particularly want the $ M $ operator to act on the second qubit and meanwhile leave the first qubit unchanged, we write the $4 \times 4$ matrix as the tensor product of an identity operator and matrix M such that

$ I \otimes M = \I \otimes  \mymatrix{c}{ 0.3 & 0.6 \\ 0.7 & 0.4  } = \mymatrix{cccc} { 0.3 & 0.6 & 0 & 0 \\ 0.7 & 0.4 & 0 & 0 \\ 0 & 0 & 0.3 & 0.6 \\ 0 & 0& 0.7 & 0.4 }.   $

In this way, the identity operator and the M operator act on first and second qubits, respectively, due to the tensor product's definition.

<h3> Task 1</h3>

We have two bits. What is $ (4 \times 4) $-dimensional matrix representation of the probabilistic operator $ M =  \mymatrix{c}{ 0.2 & 0.7 \\ 0.8 & 0.3  } $ applied to the first bit?

In [4]:
import numpy as np
state = np.kron( np.array([[1],[0]]),np.array([[1],[0]]) )

print(state)
print()

op_m =   np.array([[0.2,0.7],[0.8,0.3]])

I2 = np.array([[1,0],[0,1]])

# composite operator = M (x) I
composite_op = np.kron(op_m,I2)

print(composite_op)
print()

# result = M (x) I on state
result = np.matmul(composite_op,state)

print(result)
print()



[[1]
 [0]
 [0]
 [0]]

[[0.2 0.  0.7 0. ]
 [0.  0.2 0.  0.7]
 [0.8 0.  0.3 0. ]
 [0.  0.8 0.  0.3]]

[[0.2]
 [0. ]
 [0.8]
 [0. ]]



<a href="CS40_Operators_on_Multiple_Bits_Solutions.ipynb#task1">click for our solution</a>

<h3> Task 2</h3>

We have three bits. What is $ (8 \times 8) $-dimensional matrix representation of the probabilistic operator $ M =  \mymatrix{c}{ 0.9 & 0.4 \\ 0.1 & 0.6  } $ applied to the second bit?

In [6]:
import numpy as np
state = np.kron( np.array([[1],[0]]), np.kron(np.array([[1],[0]]),np.array([[1],[0]]) ) )

print(state)
print()

op_m =   np.array([[0.9,0.4],[0.1,0.6]])

I2 = np.array([[1,0],[0,1]])

# composite operator = M (x) I
composite_op = np.kron(I2, np.kron(op_m,I2))

print(composite_op)
print()

# result = M (x) I on state
result = np.matmul(composite_op,state)

print(result)
print()


[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]

[[0.9 0.  0.4 0.  0.  0.  0.  0. ]
 [0.  0.9 0.  0.4 0.  0.  0.  0. ]
 [0.1 0.  0.6 0.  0.  0.  0.  0. ]
 [0.  0.1 0.  0.6 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.9 0.  0.4 0. ]
 [0.  0.  0.  0.  0.  0.9 0.  0.4]
 [0.  0.  0.  0.  0.1 0.  0.6 0. ]
 [0.  0.  0.  0.  0.  0.1 0.  0.6]]

[[0.9]
 [0. ]
 [0.1]
 [0. ]
 [0. ]
 [0. ]
 [0. ]
 [0. ]]



<a href="CS40_Operators_on_Multiple_Bits_Solutions.ipynb#task2">click for our solution</a>

### Two bits operators

We start with an easy example. 

We have three bits and we apply the probabilistic operator 
$ M = \mymatrix{rrrr}{0.05 & 0 & 0.70 & 0.60 \\ 0.45 & 0.50 & 0.20 & 0.25 \\ 0.20 & 0.35 & 0.10 & 0 \\ 0.30 & 0.15 & 0 & 0.15 } $ to the first and second bits. Then, the corresponding $ (8 \times 8) $-dimensional matrix is $ M \otimes I $, where $I$ is the $(2 \times 2)$-dimensional Identity matrix.

If $ M $ is applied to the second and third bits, then the corresponding matrix is $ I \otimes M $.

**What if $ M $ is applied to the first and third bits?**

We pick an example transition: it is given in $ M $ that $ \greenbit{0} \brownbit{1}  \xrightarrow{0.35} \greenbit{1} \brownbit{0}  $.  
- That is, when the first bit is 0 and third bit is 1, the first bit is set to 1 and the the third bit is set to 0 with probability 0.35:

$$ \myarray{ccccc}{\mbox{first-bit} & \mbox{third-bit} & probability & \mbox{first-bit} & \mbox{third-bit} \\ \greenbit{0} & \brownbit{1} & \xrightarrow{0.35} & \greenbit{1} & \brownbit{0} }  $$

- We put the second bit in the picture by assuming that the identity operator is applied to it:

$$ 
\myarray{ccccccc}{
\mbox{first-bit} & \mbox{second-bit} & \mbox{third-bit} & probability & \mbox{first-bit} & \mbox{second-bit} & \mbox{third-bit} \\ 
\greenbit{0} & \bluebit{0} & \brownbit{1} & \xrightarrow{0.35} & \greenbit{1} & \bluebit{0} & \brownbit{0}  \\
\greenbit{0} & \bluebit{1} & \brownbit{1} & \xrightarrow{0.35} & \greenbit{1} & \bluebit{1} & \brownbit{0} \\
\\ \hline \\
\greenbit{0} & \bluebit{0} & \brownbit{1} & \xrightarrow{0} & \greenbit{1} & \bluebit{1} & \brownbit{0}  \\
\greenbit{0} & \bluebit{1} & \brownbit{1} & \xrightarrow{0} & \greenbit{1} & \bluebit{0} & \brownbit{0}
}
$$

<h3> Task 3</h3>

Why are the last two transition probabilities zeros in the above table?

<h3> Task 4</h3>

We have three bits and the  probabilistic operator 
$ M = \mymatrix{rrrr}{0.05 & 0 & 0.70 & 0.60 \\ 0.45 & 0.50 & 0.20 & 0.25 \\ 0.20 & 0.35 & 0.10 & 0 \\ 0.30 & 0.15 & 0 & 0.15 } $ is applied to the first and third bits. 

What is the corresponding the $(8 \times 8)$-dimensional matrix applied to the whole system?

*You may solve this task by using python.*

In [1]:
# the given matrix
M = [
    [0.05, 0, 0.70, 0.60],
    [0.45, 0.50, 0.20, 0.25],
    [0.20, 0.35, 0.10, 0],
    [0.30, 0.15, 0, 0.15]
]

import numpy as np
state88 = np.kron( np.array([[1],[0]]), np.kron(np.array([[1],[0]]),np.array([[1],[0]]) ) )

print(state88)
print(np.shape(state88))
print()

M44 =   np.array(M)

print(M44)
print(np.shape(M44))
print()

I22 = np.array([[1,0],[0,1]])

print(I22)
print(np.shape(I22))
print()

# composite operator = M (x) I (X) M
composite_op = np.kron(M44, np.kron(I22,M44))

print(composite_op)
print(np.shape(composite_op))
print()

# result = M (x) I on state
result = np.matmul(composite_op,state88)

print(result)
print()

[[1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
(8, 1)

[[0.05 0.   0.7  0.6 ]
 [0.45 0.5  0.2  0.25]
 [0.2  0.35 0.1  0.  ]
 [0.3  0.15 0.   0.15]]
(4, 4)

[[1 0]
 [0 1]]
(2, 2)

[[0.0025 0.     0.035  ... 0.     0.     0.    ]
 [0.0225 0.025  0.01   ... 0.     0.     0.    ]
 [0.01   0.0175 0.005  ... 0.     0.     0.    ]
 ...
 [0.     0.     0.     ... 0.075  0.03   0.0375]
 [0.     0.     0.     ... 0.0525 0.015  0.    ]
 [0.     0.     0.     ... 0.0225 0.     0.0225]]
(32, 32)



ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 8 is different from 32)

<a href="CS40_Operators_on_Multiple_Bits_Solutions.ipynb#task4">click for our solution</a>

### Controlled operators

The matrix form of the controlled-NOT operator is as follows:

$ CNOT = \mymatrix{cc|cc}{ 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ \hline 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 } 
= \mymatrix{c|c}{ I & \mathbf{0} \\ \hline \mathbf{0} & X},
$
where $ X $ denotes the NOT operator.

Similarly, for a given single bit operator $ M $, we can define the controlled-$M$ operator (where the first bit is the control bit and the second bit is target bit) as follows:

$ CM = \mymatrix{c|c}{ I & \mathbf{0} \\ \hline \mathbf{0} & M } $

By definition:
* when the first bit is 0, the identity is applied to the second bit, and
* when the first bit is 1, the operator $ M $ is applied to the second bit. 

Here we observe that the matrix $ CM $ has a nice form because the first bit is control bit. The matrix $ CM $ given above is divided into four sub-matrices based on the states of the first bit. Then, we can follow that
* the value of the first bit never changes, and so the off diagonal sub-matrices are zeros; 
* when the first bit is 0, the identity is applied to the second bit, and so top-left matrix is $ I $; and, 
* when the first bit is 1, the operator $ M $ is applied to the second bit, and so the bottom-right matrix is $ M $.

<h3> Task 5</h3>

Let $ M = \mymatrix{cc}{0.7 & 0.4 \\ 0.3 & 0.6} $ be a single bit operator. What is the matrix form of the controlled-$M$ operator where the first bit is the target bit and the second bit is the control bit.

$$
CM = \begin{bmatrix} I & 0 \\ 0 & M \\ \end{bmatrix} =
\begin{bmatrix} 
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0.7 & 0.4 \\
0 & 0 & 0.3 & 0.6 \\
\end{bmatrix}
$$

<a href="CS40_Operators_on_Multiple_Bits_Solutions.ipynb#task5">click for our solution</a>

### Controlled operator activated when in state 0 

For a given single bit operator $ M $, **how can we obtain the following operator** by using the operator $ CM $?

$ C_0M = \mymatrix{c|c}{ M & \mathbf{0} \\ \hline \mathbf{0} & I } $

Controlled operator are defined to be triggered when the control bit is in state 1. In this example, we expect it to be triggered when the control bit is in state 0.

Here we can use a simple trick. We first apply NOT operator to the first bit, and then the CM operator, and again NOT operator. In this way, we guarentee that $ M $ is applied to the second bit if the first bit is state 0 and do nothing if the first bit is in state 1. In short:

$$ C_0M = (X \otimes I) \cdot (CM) \cdot ( X \otimes I ). $$

<h3> Task 6</h3>

Verify that $ C_0M = (X \otimes I) \cdot (CM) \cdot ( X \otimes I ) = \mymatrix{c|c}{ M & \mathbf{0} \\ \hline \mathbf{0} & I }  $.

<a href="CS40_Operators_on_Multiple_Bits_Solutions.ipynb#task6">click for our solution</a>

<h3> Task 7</h3>

For the given two single bit operators $ M $ and $ N $, let $ CM $ and $ CN $ be the controlled-$M$ and controlled-$N$ operators. By using $ X $, $ CM $, and $ CN $ operators, how can we obtain the operator $ \mymatrix{c|c}{ M & \mathbf{0} \\ \hline \mathbf{0} & N} $?
